const getCardData = (t) => [
  {
    id: 'enprices',
    imageUrl: '/ENPRICES.png',
    imageAlt: t('card.enprices.imageAlt'),
    title: t('card.enprices.title'),
    description: t('card.enprices.description'),
    onCustomize: () => console.log('Customize electricity visualization'),
    onGoToTool: () => console.log('Go to electricity tool'),
  },
  {
    id: 'ensankey',
    imageUrl: '/SANKEY.png',
    imageAlt: t('card.ensankey.imageAlt'),
    title: t('card.ensankey.title'),
    description: t('card.ensankey.description'),
    onCustomize: () => console.log('Customize gas visualization'),
    onGoToTool: () => console.log('Go to gas tool'),
  },
  {
    id: 'enmonthly',
    imageUrl: '/ENMONTHLY.png',
    imageAlt: t('card.enmonthly.imageAlt'),
    title: t('card.enmonthly.title'),
    description: t('card.enmonthly.description'),
    onCustomize: () => console.log('Customize gas visualization'),
    onGoToTool: () => console.log('Go to gas tool'),
  },
  {
    id: 'entrade',
    imageUrl: '/ENTRADE.png',
    imageAlt: t('card.entrade.imageAlt'),
    title: t('card.entrade.title'),
    description: t('card.entrade.description'),
    onCustomize: () => console.log('Customize gas visualization'),
    onGoToTool: () => console.log('Go to gas tool'),
  },
  {
    id: 'enbal',
    imageUrl: '/ENBAL.png',
    imageAlt: t('card.enbal.imageAlt'),
    title: t('card.enbal.title'),
    description: t('card.enbal.description'),
    onCustomize: () => console.log('Customize gas visualization'),
    onGoToTool: () => console.log('Go to gas tool'),
  },
  {
    id: 'endash',
    imageUrl: '/ENDASH.png',
    imageAlt: t('card.endash.imageAlt'),
    title: t('card.endash.title'),
    description: t('card.endash.description'),
    onCustomize: () => console.log('Customize gas visualization'),
    onGoToTool: () => console.log('Go to gas tool'),
  },
  {
    id: 'shedthelight',
    imageUrl: '/SHEDLIGHT.png',
    imageAlt: t('card.shedthelight.imageAlt'),
    title: t('card.shedthelight.title'),
    description: t('card.shedthelight.description'),
    onCustomize: () => console.log('Customize gas visualization'),
    onGoToTool: () => console.log('Go to gas tool'),
  },
  {
    id: 'EnergyScenarios',
    imageUrl: '/ENSCENARIOS.jpg',
    imageAlt: t('card.EnergyScenarios.imageAlt'),
    title: t('card.EnergyScenarios.title'),
    description: t('card.EnergyScenarios.description'),
    onCustomize: () => console.log('Customize gas visualization'),
    onGoToTool: () => console.log('Go to gas tool'),
  },
];

export default getCardData;
